### ISSUE TITLE
Avoid re-rendering UI sections that contain focused elements

### ISSUE THREAD

**Issue by afercia** [coreymckrill/nearby-wordpress-events#43] opened 2017-04-23 20:10 UTC
I'm sorry I'm afraid this is going to be a big one 🙂  but it's something worth discussing.

I was wondering how the form gets collapsed after it's submitted, turned out it's not collapsed but it's the whole JS template that gets re-rendered. Currently, the whole template gets rendered on init, and always on `done` and `fail`. In the screenshot below I've highlighted the section that gets re-rendered:

![screen shot 2017-04-22 at 17 47 17](https://cloud.githubusercontent.com/assets/1682452/25316759/f6c43bea-286c-11e7-8404-1bc5c633bb5a.png)

It includes the input field and the submit form.

The point is, when submitting, the re-rendering happens when the input field or the submit button are the currently focused element. When this happens, focus is lost. This can have a devastating impact for keyboard accessibility and screen reader users.

Some browsers (Firefox, Chrome from version 50, Safari from version 10) try to be smart and try to keep focus "in place". They use a sort of internal pointer to the last focused element and when this gets removed from the DOM or hidden, they try to start again the tab order from the nearest "parent" focusable element. This sometimes works nicely, sometimes not. It actually depends on how big is the chunk of HTML that gets re-rendered. Other browsers completely lose focus, and users are forced to start again the tab order from the document root.

It gets more complicated when assistive technologies come into play, as users would lose context and they won't have a clue why something just "disappeared" from the page.

For accessibility, there should always be a clear indication of the currently focused element and it should never be removed, hidden, or re-rendered. 

I'm aware this would require some re-working of the widget, but it's also a great opportunity to experiment best practices and do some research, especially if WordPress is more and more going to use JavaScript for the UI.

Ideally, for a good level of accessibility, JavaScript-based UIs should try to follow a few principles:
- limit re-renderings as much as possible
- never re-render focused elements
- re-render just the UI sections that actually need to be re-rendered

Also, making the JS templates as small as possible, makes a lot of sense to me.

In this case, the form (input field and submit button) doesn't really need to be re-rendered. The only sections that need to be updated are the text before the form and the list of events after the form.

One way to improve things would be splitting the template in 2 (maybe more?) parts and output the form on the PHP side. Then, the re-rendering could be triggered just on the UI sections before and after the form. Well, actually it doesn't make a difference if the form is generated with PHP or a JS template, the important thing is it doesn't get re-rendered 🙂 

I've experimented a bit and seems to me this is definitely feasible. However, for the same reason, the form shouldn't automatically collapse when submitted, it should always stay visible.

**Comment by iandunn** [comment] 2017-04-24 22:08
Thanks Andrea! This definitely sounds like something we should fix.

> the form shouldn't automatically collapse when submitted, it should always stay visible.

That confuses me, though. It seems odd that an application could never hide a form in an accessible way, even when the form is no longer needed/wanted.

Would it be possible to move the programmatically focus back to the pencil icon, and use `ally.speak()` to inform screen readers that it was moved? Or something else?

**Comment by coreymckrill** [comment] 2017-04-25 00:10
^ Here is an initial commit for the refactor.

**Comment by afercia** [comment] 2017-04-25 06:51
> Would it be possible to programmatically move the focus back to the pencil icon, and use a11y.speak() to inform screen readers that it was moved? Or something else?

Yep that's an option. Ideally, the best option is always "don't do anything, just keep the native behavior" but if you really, really, want then you should handle focus programmatically.

I wonder if collapsing the form would be really useful though. Think at some mistyped location or any error users might do while entering the location. They submit, form closes, and then they realize their mistake. They would be forced to re-open the form again.

After all, entering the location and saving it's something that will likely happen once or a few times during the initial configuration of the widget then users will forget this setting and never (or rarely) come back. So keeping it open could be an option.

**Comment by iandunn** [comment] 2017-04-25 15:23
Aaaah, I think I see; you're not suggesting that the form always be displayed, but only that once the user opens the form, it should remain open until they reload the page. Is that correct?

If that's it, then I don't have any objections to that. I was just worried about the form cluttering the UI after the point where they'd always settled into a location and won't ever be changing it again.

**Comment by afercia** [comment] 2017-04-25 15:25
Correct! 😄

**Comment by coreymckrill** [comment] 2017-04-25 20:10
> once the user opens the form, it should remain open until they reload the page.

This is actually how it works now with the refactor. And if on the initial page load, no valid location is available, the form opens automatically.

**Comment by iandunn** [comment] 2017-04-26 16:59
I think I saw some cases where it still gets closed. I'll try to reproduce that.

**Comment by iandunn** [comment] 2017-04-26 23:57
It looks like the form stays open after successful queries, but not when a location couldn't be found, or there was an error in the AJAX request. When those happen, the form is hidden.

**Comment by iandunn** [comment] 2017-05-03 20:59
@afercia: I think this is all sorted now. Would you mind testing again, and letting me know what you think?

**Comment by afercia** [comment] 2017-05-04 20:40
@iandunn I think splitting the templates works perfectly for a11y and also shows some best practices that I hope will be adopted in future projects :)

I'd consider to change just one thing: remove
`$form.find( 'input[name="nearbywp-location"]' ).focus();`
for two reasons:
- when opening the form, screen readers don't have enough time to announce `expanded` for the aria-expanded state, because the input field gets focused immediately and will be announced
- when submitting the form, that line causes the input field to be re-focused again, seems because `app.toggleLocationForm( 'show' );` always run when submitting

**Comment by iandunn** [comment] 2017-05-04 20:48
Ah, great catch, I'll take that out. Thanks :)

**Comment by iandunn** [comment] 2017-05-09 15:10
We've gotten some feedback about UX being hurt by the form not closing automatically after submission, so I'm going to reopen this.

@afercia, do you have any ideas about how to restore that without hurting a11y?

**Comment by iandunn** [comment] 2017-05-11 18:52
Moved to https://core.trac.wordpress.org/ticket/40735

**Closed by iandunn** 2017-05-11 18:52 UTC
Labels: bug, high priority
